TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 5000
  DATASET: 'CAMUS_cv_1'
  INPUT_SIZE: 256
  NUM_KPTS: 107
  NUM_KPTS_MULTISTRUCTURE: [ 43,21,43 ]
MODEL:
  NAME: 'GCN_multi_small'
  BACKBONE: 'mobilenet2'
  LOSS_FUNC: ['L2']
AUG:
  METHOD: 'strongkeep'
  PROB: 0.90
SOLVER:
  BASE_LR: 1.0e-05
DISPLACEMENT_MODEL: False